[Interface]
PrivateKey = 2CBLOq9G0ClzbjsrD2/Hxt/0fRg6HTAEYpTL66f7dGc=
Address = 10.0.61.6/32

[Peer]
PublicKey = YxV8azKU+GFRzBdcoZTpQjlRfVsMthcn5iLQvwtFQH0=
AllowedIPs = 192.168.3.0/24
Endpoint = 188.235.145.88:13233